const Synonyms = {
  book: ["Novel", "Tome", "Volume", "Manuscript"],
  chair: ["Seat", "Armchair", "Recliner", "Throne"],
  table: ["Desk", "Dining table", "Counter", "Board"],
  car: ["Automobile", "Vehicle", "Auto", "Motorcar"],
  pen: ["Writing instrument", "Ballpoint", "Fountain pen", "Quill"],
  computer: ["PC", "Laptop", "Desktop", "Machine"],
  phone: ["Mobile", "Smartphone", "Cellphone", "Handset"],
  house: ["Home", "Residence", "Dwelling", "Abode"],
  shoes: ["Footwear", "Sneakers", "Boots", "Sandals"],
  key: ["Passkey", "Code", "Access", "Clue"],
  door: ["Entrance", "Gateway", "Portal", "Access point"],
  cup: ["Mug", "Goblet", "Chalice", "Tumbler"],
  clock: ["Timepiece", "Watch", "Chronometer", "Timer"],
  bag: ["Sack", "Tote", "Backpack", "Pouch"],
  paper: ["Document", "Sheet", "Manuscript", "Parchment"],
  bed: ["Mattress", "Cot", "Bunk", "Sleeping platform"],
  window: ["Pane", "Glass", "Opening", "Casement"],
  tree: ["Plant", "Flora", "Timber", "Woody plant"],
  watch: ["Timepiece", "Wristwatch", "Chronograph", "Stopwatch"],
  hat: ["cap", "bonnet", "headgear", "beanie"],
  dog: ["canine", "pooch", "hound", "mutt"],
  cat: ["feline", "kitty", "puss", "tabby"],
  bird: ["avian", "feathered friend", "fowl", "songbird"],
  fish: ["aquatic creature", "finned friend", "marine life", "swimmer"],
  elephant: ["pachyderm", "giant", "mammoth", "tusker"],
  lion: ["big cat", "king of the jungle", "predator", "roarer"],
  tiger: ["striped cat", "big feline", "predator", "bengal"],
  bear: ["ursine", "grizzly", "bruin", "cub"],
  horse: ["equine", "stallion", "mare", "pony"],
  rabbit: ["bunny", "hare", "lapin", "cony"],
  monkey: ["primate", "ape", "simian", "chimpanzee"],
  snake: ["serpent", "reptile", "python", "cobra"],
  turtle: ["tortoise", "terrapin", "shelled reptile", "slowpoke"],
  dolphin: ["marine mammal", "porpoise", "flipper", "cetacean"],
  penguin: ["flightless bird", "flipper bird", "antarctic bird", "rookery resident"],
  giraffe: ["long-necked mammal", "towering creature", "African herbivore", "spotted neck"],
  kangaroo: ["marsupial", "roo", "jumper", "hopper"],
  zebra: ["striped horse", "African equid", "zebroid", "wild grazer"],
  wolf: ["canine", "wild dog", "lupine", "howler"],
  cheetah: ["big cat", "spotted feline", "sprint specialist", "swift predator"],
  cow: ["bovine", "heifer", "cattle", "moo-cow"],
  sheep: ["ewe", "ram", "flock", "woolly mammal"],
  chicken: ["hen", "rooster", "poultry", "clucker"],
  duck: ["waterfowl", "quacker", "mallard", "webbed friend"],
  frog: ["amphibian", "toad", "croaker", "leaper"],
  butterfly: ["flutterer", "insect with wings", "colorful flyer", "moth"],
  bee: ["pollinator", "honey-maker", "stinger", "buzzing insect"],
  spider: ["arachnid", "web-weaver", "eight-legged creature", "spinner"],
  snail: ["gastropod", "slowpoke", "shell-dweller", "slimy crawler"],
  octopus: ["cephalopod", "eight-armed creature", "ocean mollusk", "ink-squirter"],
  person: ["individual", "human being", "someone", "mortal"],
  time: ["moment", "era", "duration", "chronology"],
  year: ["annual", "365 days", "calendar year", "annum"],
  way: ["path", "route", "method", "direction"],
  day: ["24 hours", "sunlight period", "diurnal cycle", "daylight"],
  thing: ["object", "item", "entity", "article"],
  man: ["male", "guy", "fellow", "gentleman"],
  world: ["planet", "globe", "Earth", "cosmos"],
  life: ["existence", "living", "being", "lifeworld"],
  hand: ["palm", "manual extremity", "grasping organ", "digit"],
  part: ["portion", "segment", "fragment", "component"],
  child: ["kid", "youth", "offspring", "youngster"],
  eye: ["visual organ", "sight organ", "orb", "peeper"],
  woman: ["female", "lady", "gal", "dame"],
  place: ["location", "spot", "site", "area"],
  work: ["job", "employment", "occupation", "task"],
  week: ["seven days", "weeklong", "workweek", "seven-day period"],
  case: ["instance", "scenario", "situation", "example"],
  point: ["argument", "topic", "detail", "aspect"],
  government: ["administration", "authority", "regime", "ruling body"],
  childhood: ["early years", "youth", "infancy", "formative years"],
  dream: ["aspiration", "fantasy", "vision", "goal"],
  goal: ["objective", "target", "ambition", "achievement"],
  power: ["authority", "control", "influence", "dominance"],
  money: ["currency", "wealth", "finance", "capital"],
  success: ["achievement", "accomplishment", "triumph", "victory"],
  failure: ["setback", "defeat", "loss", "non-success"],
  happiness: ["joy", "contentment", "bliss", "pleasure"],
  friendship: ["companionship", "camaraderie", "alliance", "acquaintance"],
  education: ["learning", "instruction", "knowledge", "schooling"],
  health: ["well-being", "fitness", "vitality", "soundness"],
  home: ["residence", "dwelling", "house", "abode"],
  nature: ["natural world", "environment", "landscape", "wilderness"],
  business: ["commerce", "industry", "enterprise", "company"],
  weekend: ["Saturday and Sunday", "two days off", "end of the week", "leisure time"],
  experience: ["encounter", "event", "incident", "occasion"],
  adventure: ["exploit", "journey", "quest", "enterprise"],
  bubble: ["sphere", "balloon", "air pocket", "foam"],
  guitar: ["stringed instrument", "acoustic", "electric", "axe"],
  window: ["pane", "opening", "portal", "glass"],
  dragon: ["mythical creature", "serpent", "mythical beast", "fire-breather"],
  rocket: ["spacecraft", "missile", "space vehicle", "projectile"],
  circle: ["round", "ring", "loop", "cycle"],
  basket: ["hamper", "woven container", "basketful", "bin"],
  coffee: ["brew", "java", "caffeine", "cup of Joe"],
  flower: ["blossom", "bloom", "petal", "floral"],
  lemon: ["citrus fruit", "sour fruit", "yellow fruit", "tart"],
  radio: ["broadcast", "transmission", "airwaves", "wireless"],
  table: ["furniture", "desk", "surface", "board"],
  ocean: ["sea", "deep", "marine", "water"],
  rabbit: ["bunny", "hare", "lapin", "cony"],
  wallet: ["billfold", "purse", "money holder", "cardholder"],
  bridge: ["span", "crossing", "arch", "viaduct"],
  love: ["affection", "devotion", "passion", "romance"],
  friend: ["companion", "buddy", "pal", "chum"],
  family: ["relatives", "kin", "household", "clan"],
  house: ["home", "residence", "dwelling", "abode"],
  car: ["automobile", "vehicle", "auto", "motorcar"],
  money: ["currency", "wealth", "finance", "capital"],
  school: ["educational institution", "learning center", "academy", "college"],
  book: ["novel", "volume", "publication", "text"],
  city: ["metropolis", "urban area", "municipality", "town"],
  food: ["nourishment", "nutrition", "edibles", "fare"],
  water: ["liquid", "H2O", "aquatic substance", "beverage"],
  air: ["atmosphere", "gas", "breath", "wind"],
  health: ["well-being", "fitness", "vitality", "soundness"],
  mind: ["intellect", "brain", "consciousness", "thoughts"],
  hear: ["listen", "perceive", "attend", "detect"],
  music: ["melody", "tune", "harmony", "composition"],
  art: ["creative expression", "fine arts", "craftsmanship", "creativity"],
  computer: ["PC", "machine", "device", "digital tool"],
  internet: ["web", "online", "cyberspace", "world wide web"],
  friendship: ["companionship", "camaraderie", "alliance", "acquaintanceship"],
  environment: ["surroundings", "ecosystem", "habitat", "setting"],
  technology: ["innovation", "advancement", "high-tech", "tools"],
  communication: ["interaction", "exchange", "conveyance", "dialogue"],
  culture: ["tradition", "customs", "heritage", "way of life"],
  problem: ["issue", "challenge", "dilemma", "obstacle"],
  solution: ["resolution", "answer", "fix", "remedy"],
  development: ["progress", "advancement", "growth", "evolution"],
  economy: ["financial system", "market", "commerce", "economic structure"],
  industry: ["sector", "business", "trade", "manufacturing"],
  opportunity: ["chance", "prospect", "opening", "possibility"],
  knowledge: ["wisdom", "understanding", "information", "awareness"],
  relationship: ["connection", "bond", "association", "link"],
  difference: ["disparity", "distinction", "contrast", "discrepancy"],
  decision: ["choice", "judgment", "selection", "verdict"],
  future: ["tomorrow", "upcoming time", "prospective", "tomorrowland"],
  spider: ["arachnid", "web-spinner", "eight-legged creature", "spinner"],
  penguin: ["flightless bird", "flipper bird", "antarctic bird", "rookery resident"],
  ant: ["insect", "tiny creature", "colony worker", "formicidae"],
  mud: ["muck", "clay", "soil", "silt"],
  earth: ["planet", "world", "globe", "sphere"],
  hair: ["strand", "tresses", "locks", "follicles"],
  pet: ["animal companion", "domesticated friend", "furry friend", "critter"],
  pig: ["swine", "hog", "porcine", "porker"],
  bird: ["avian", "feathered friend", "fowl", "winged creature"],
  barn: ["shed", "stable", "farm building", "warehouse"],
  snap: ["crack", "pop", "click", "snarl"],
  heat: ["warmth", "temperature", "intensity", "fever"],
  hit: ["strike", "impact", "blow", "punch"],
  ice: ["frost", "frozen water", "glacier", "gelid substance"],
  pirate: ["buccaneer", "seafarer", "privateer", "raider"],
  cave: ["cavern", "grotto", "subterranean space", "hole"],
  pact: ["agreement", "treaty", "deal", "accord"],
  rice: ["grain", "staple", "cereal", "paddy"],
  rate: ["speed", "pace", "frequency", "evaluation"],
  vice: ["sin", "immorality", "bad habit", "corruption"],
  carpet: ["rug", "floor covering", "mat", "textile"],
  char: ["burn", "scorch", "blacken", "singe"],
  peach: ["fruit", "nectarine", "apricot", "stone fruit"],
  teach: ["instruct", "educate", "train", "inform"],
  braid: ["plait", "twist", "weave", "interlace"],
  brain: ["mind", "intellect", "cerebrum", "mental faculty"],
  bind: ["tie", "fasten", "attach", "connect"],
  bride: ["wife-to-be", "spouse", "fiancée", "marriage partner"],
  drape: ["curtain", "hang", "cover", "decorate"],
  drain: ["exhaust", "empty", "deplete", "sap"],
  diner: ["restaurant", "eatery", "café", "bistro"],
  dine: ["eat", "feast", "consume", "partake"],
  earn: ["gain", "receive", "acquire", "fetch"],
  end: ["conclusion", "termination", "finish", "closure"],
  pad: ["cushion", "mat", "padding", "cotton"],
  pan: ["pot", "cooking vessel", "skillet", "saucepan"],
  pane: ["windowpane", "glass", "panel", "sheet"],
  pair: ["couple", "duo", "twosome", "brace"],
  pain: ["discomfort", "ache", "hurt", "suffering"],
  pear: ["fruit", "pyrus", "edible", "juicy"],
  pine: ["conifer", "evergreen", "tree", "lumber"],
  pride: ["self-esteem", "dignity", "self-respect", "confidence"],
  rain: ["precipitation", "downpour", "shower", "drizzle"],
  raise: ["lift", "elevate", "hoist", "boost"],
  ride: ["journey", "drive", "trip", "excursion"],
  rib: ["bone", "costa", "rack", "spare rib"],
  rise: ["ascend", "climb", "lift", "uprise"],
  side: ["flank", "boundary", "edge", "margin"],
  snare: ["trap", "net", "lure", "capture"],
  spread: ["expand", "extend", "unfold", "disperse"],
  saber: ["sword", "blade", "cutlass", "weapon"],
  sane: ["rational", "sound", "sensible", "logical"],
  sand: ["grains", "beach", "granules", "shingle"],
  send: ["dispatch", "transmit", "forward", "mail"],
  seer: ["prophet", "visionary", "oracle", "clairvoyant"],
  sine: ["trigonometric function", "curve", "wave", "oscillation"],
  span: ["distance", "reach", "extent", "interval"],
  spin: ["rotate", "twirl", "revolve", "whirl"],
  spine: ["backbone", "vertebrae", "spinal column", "back"],
  bane: ["curse", "plague", "misfortune", "bane"],
  bean: ["legume", "seed", "pulse", "haricot"],
  bare: ["naked", "exposed", "uncovered", "nude"],
  brand: ["mark", "logo", "label", "trademark"],
  scribe: ["scribe", "writer", "scribe", "copyist"],
  arise: ["emerge", "appear", "come forth", "develop"],
  bends: ["curves", "angles", "turns", "twists"],
  band: ["group", "ensemble", "musical group", "band"],
  pander: ["cater to", "indulge", "gratify", "please"],
  pared: ["peeled", "trimmed", "shaved", "cut"],
  resin: ["sap", "gum", "substance", "extract"],
  rides: ["travels", "journeys", "drives", "commutes"],
  nerd: ["geek", "bookworm", "intellectual", "dweeb"],
  snipe: ["criticize", "mock", "taunt", "sneer"],
  snider: ["sarcastic", "cutting", "sardonic", "mocking"],
  sabre: ["sword", "blade", "cutlass", "weapon"],
  serin: ["songbird", "finch", "canary", "warbler"],
  spared: ["saved", "rescued", "preserved", "forgiven"],
  panier: ["basket", "hamper", "container", "tray"],
  nadir: ["lowest point", "bottom", "low", "depth"],
  braised: ["cooked", "stewed", "simmered", "roasted"],
  snare: ["trap", "entrap", "ambush", "capture"],
  debris: ["remains", "wreckage", "ruins", "detritus"],
  braid: ["plait", "twist", "weave", "intertwine"],
  napes: ["back of the neck", "nape", "scruff", "cervix"],
  bedpan: ["commode", "chamber pot", "portable toilet", "bedside toilet"],
  rapine: ["plunder", "pillage", "loot", "robbery"],
  insider: ["informed person", "knowledgeable person", "authority", "expert"],
  bud: ["sprout", "shoot", "growth", "blossom"],
  bug: ["insect", "pest", "creature", "invertebrate"],
  burp: ["belch", "eructation", "expulsion of gas", "belching"],
  burden: ["load", "weight", "onus", "responsibility"],
  budge: ["move", "shift", "stir", "inch"],
  brine: ["saltwater", "seawater", "briny water", "saline solution"],
  burn: ["scorch", "char", "ignite", "inflame"],
  ding: ["dent", "scratch", "nick", "imperfection"],
  dire: ["grim", "dreadful", "severe", "terrible"],
  dune: ["sand hill", "sand mound", "sand dune", "sandbank"],
  drug: ["substance", "medication", "pharmaceutical", "narcotic"],
  grin: ["smile", "smirk", "beam", "smile broadly"],
  grind: ["crush", "grate", "mill", "pulverize"],
  grid: ["framework", "network", "grating", "matrix"],
  grip: ["hold", "grasp", "clasp", "clench"],
  guide: ["lead", "direct", "instruct", "mentor"],
  grub: ["food", "chow", "nourishment", "fare"],
  nudge: ["prod", "poke", "push", "jab"],
  nude: ["naked", "unclothed", "bare", "naked body"],
  rein: ["control", "restraint", "constraint", "direction"],
  rend: ["tear", "rip", "split", "shred"],
  rude: ["impolite", "discourteous", "uncivil", "crude"],
  ruin: ["destroy", "wreck", "demolish", "devastate"],
  run: ["jog", "sprint", "dash", "jog"],
  unbind: ["release", "free", "untie", "detach"],
  under: ["beneath", "below", "lower than", "underneath"],
  bruin: ["brown", "grizzly", "bear", "ursine"],
  rebind: ["reattach", "bind again", "tie up", "fasten"],
  buried: ["interred", "entombed", "covered", "hidden"],
  burin: ["engraving tool", "graver", "chisel", "incising tool"],
  unbred: ["unraised", "unfed", "unreared", "unbred"],
  reding: ["rinsing", "flushing", "washing", "cleansing"],
  inured: ["accustomed", "habituated", "hardened", "desensitized"],
  bruined: ["brown", "colored", "tinted", "hued"],
  nudger: ["prod", "poke", "nudge", "jab"],
  bunged: ["plugged", "corked", "stopped", "sealed"],
  dubbing: ["dub", "naming", "designation", "title"],
  dinger: ["hit", "smack", "impact", "blow"],
  ring: ["circle", "loop", "band", "hoop"],
  urn: ["vase", "container", "cinerary urn", "funerary urn"],
  draw: ["pull", "haul", "tug", "drag"],
  armed: ["equipped", "armed forces", "militarized", "prepared"],
  meant: ["intended", "signified", "meant to be", "purposed"],
  trade: ["commerce", "business", "exchange", "barter"],
  tread: ["step", "walk", "pace", "march"],
  dewar: ["container", "flask", "vessel", "thermos"],
  under: ["beneath", "below", "lower than", "underneath"],
  derma: ["skin", "epidermis", "dermis", "cutis"],
  named: ["called", "designated", "entitled", "identified"],
  amend: ["modify", "alter", "revise", "correct"],
  wane: ["decrease", "diminish", "decline", "fade"],
  ante: ["bet", "wager", "stake", "ante-up"],
  taw: ["tan", "pale", "blanch", "whiten"],
  award: ["prize", "honor", "reward", "trophy"],
  wader: ["boot", "hip boot", "waterproof boot", "fishing boot"],
  rawl: ["cry out", "yell", "shout", "scream"],
  tan: ["brown", "bronze", "beige", "suntan"],
  mat: ["rug", "carpet", "floor covering", "doormat"],
  dew: ["moisture", "condensation", "wetness", "droplets"],
  date: ["appointment", "meeting", "rendezvous", "assignation"],
  wand: ["staff", "stick", "rod", "baton"],
  dawn: ["daybreak", "sunrise", "morning", "first light"],
  rend: ["tear", "rip", "split", "shred"],
  dart: ["projectile", "arrow", "javelin", "spear"],
  ward: ["district", "zone", "area", "region"],
  tear: ["rip", "shred", "split", "rend"],
  dear: ["beloved", "precious", "loved one", "darling"],
  want: ["desire", "crave", "long for", "wish for"],
  read: ["peruse", "scan", "examine", "study"],
  mate: ["companion", "partner", "friend", "comrade"],
  tame: ["domesticated", "trained", "docile", "subdued"],
  rate: ["evaluate", "assess", "appraise", "judge"],
  near: ["close", "proximate", "adjacent", "nearby"],
  eare: ["air", "melody", "tune", "song"],
  dare: ["challenge", "defy", "brave", "confront"],
  darted: ["hurried", "rushed", "sprinted", "scuttled"],
  wanted: ["desired", "sought after", "in demand", "coveted"],
  warmed: ["heated", "warmed up", "thawed", "heated"],
  disc: ["disk", "record", "platter", "compact disc"],
  sun: ["star", "sunlight", "daystar", "solar orb"],
  scum: ["filth", "crud", "slime", "debris"],
  sin: ["wrongdoing", "transgression", "offense", "misdeed"],
  bat: ["club", "stick", "racket", "bludgeon"],
  rat: ["rodent", "mouse", "pest", "vermin"],
  tar: ["pitch", "asphalt", "bitumen", "blacktop"],
  bar: ["pub", "tavern", "saloon", "barroom"],
  sea: ["ocean", "seas", "waters", "deep"],
  tea: ["beverage", "infusion", "brew", "herbal tea"],
  eat: ["consume", "ingest", "devour", "chow down"],
  set: ["place", "arrange", "position", "put"],
  bet: ["wager", "gamble", "risk", "stake"],
  hot: ["warm", "heated", "sizzling", "boiling"],
  hoe: ["gardening tool", "weeder", "cultivator", "digging tool"],
  toe: ["digit", "tootsie", "toe digit", "toe joint"],
  sob: ["weep", "cry", "whimper", "sigh"],
  rob: ["steal", "plunder", "thieve", "burglarize"],
  orb: ["sphere", "globe", "ball", "round object"],
  taro: ["root vegetable", "tuber", "edible tuber", "starchy root"],
  sort: ["classify", "arrange", "organize", "categorize"],
  zest: ["enthusiasm", "vigor", "energy", "zeal"],
  zero: ["nothing", "nil", "naught", "null"],
  rote: ["routine", "repetition", "drill", "memorization"],
  roes: ["fish eggs", "roe", "caviar", "fish roe"],
  rose: ["flower", "blossom", "bud", "blooms"],
  hose: ["hosiery", "stockings", "legwear", "nylons"],
  host: ["hostess", "emcee", "presenter", "anchor"],
  shot: ["attempt", "try", "effort", "undertaking"],
  star: ["celestial body", "heavenly body", "luminary", "aster"],
  tsar: ["czar", "monarch", "ruler", "sovereign"],
  boat: ["vessel", "watercraft", "ship", "craft"],
  bota: ["leather flask", "wineskin", "canteen", "flask"],
  base: ["foundation", "bottom", "base camp", "ground"],
  bate: ["restrain", "hold back", "decrease", "diminish"],
  beat: ["strike", "hit", "pound", "thump"],
  best: ["finest", "top", "supreme", "optimal"],
  arts: ["skills", "craftsmanship", "techniques", "creative skills"],
  hest: ["command", "order", "injunction", "instruction"],
  rest: ["relaxation", "repose", "leisure", "respite"],
  shoe: ["footwear", "footgear", "sandal", "boot"],
  hold: ["grasp", "grip", "clasp", "embrace"],
  echo: ["reverberation", "reflection", "resonance", "repetition"],
  field: ["area", "region", "domain", "sphere"],
  "file": ["document", "record", "paperwork", "file folder"],
  "fold": ["bend", "crease", "overlap", "double"],
  "lode": ["deposit", "vein", "mine", "ore body"],
  "old": ["ancient", "vintage", "antique", "aged"],
  "doe": ["female deer", "hind", "bambi", "fawn"],
  "dice": ["die", "cube", "ivory", "pair of dice"],
  "die": ["expire", "perish", "cease to exist", "succumb"],
  "fiddle": ["violin", "string instrument", "fiddlestick", "bowed instrument"],
  "hole": ["opening", "gap", "cavity", "void"],
  "bore": ["borehole", "drill hole", "well", "pit"],
  "road": ["street", "highway", "avenue", "thoroughfare"],
  "dome": ["dome-shaped", "rounded", "arched", "vaulted"],
  "brag": ["boast", "bragging", "vaunt", "swagger"],
  "mode": ["fashion", "style", "manner", "method"],
  "gear": ["equipment", "apparatus", "tools", "gear mechanism"],
  "bead": ["small ball", "pearl", "droplet", "globule"],
  "made": ["created", "manufactured", "produced", "fabricated"],
  "dear": ["beloved", "precious", "loved one", "darling"],
  "dare": ["challenge", "defy", "brave", "confront"],
  "drab": ["dull", "dreary", "colorless", "monotonous"],
  "game": ["sport", "contest", "match", "competition"],
  "demo": ["demonstration", "presentation", "display", "exhibition"],
  "bode": ["foretell", "predict", "prophesy", "forecast"],
  "roam": ["wander", "rove", "ramble", "rove around"],
  "ogre": ["monster", "beast", "demon", "evil spirit"],
  "grad": ["graduate", "alumnus", "former student", "degree holder"],
  "mega": ["large", "huge", "massive", "enormous"],
  "gore": ["bloodshed", "violence", "carnage", "slaughter"],
  "mare": ["female horse", "equine", "mare", "filly"],
  "goer": ["attender", "participant", "visitor", "audience member"],
  "barm": ["yeast foam", "yeast head", "beer foam", "fermentation head"],
  "beam": ["ray", "shaft", "gleam", "stream of light"],
  "bear": ["endure", "tolerate", "withstand", "sustain"],
  "brad": ["nail", "tack", "pin", "fastener"],
  "doer": ["achiever", "executor", "performer", "accomplisher"],
  "dore": ["gilded", "golden", "gold-plated"],
  "grade": ["level", "rank", "class", "tier"],
  "adobe": ["brick", "mud brick", "clay brick", "sun-dried brick"],
  "amber": ["yellow-brown", "golden", "honey-colored", "caramel"],
  "bread": ["loaf", "baked goods", "pastry", "dough"],
  "omega": ["end", "conclusion", "finale", "termination"],
  "robe": ["gown", "attire", "garment", "clothing"],
  "roam": ["wander", "stroll", "ramble", "rove"],
  "alone": ["solitary", "lonely", "isolated", "single"],
  "move": ["travel", "relocate", "shift", "change residence"],
  "love": ["affection", "devotion", "admiration", "passion"],
  "came": ["arrived", "appeared", "approached", "entered"],
  "oven": ["stove", "baking appliance", "cooker", "kiln"],
  "name": ["title", "label", "designation", "identity"],
  "vale": ["valley", "dell", "glen", "dingle"],
  "acme": ["pinnacle", "summit", "apex", "peak"],
  "loan": ["borrowing", "advance", "credit", "debt"],
  "coal": ["carbon", "charcoal", "fuel", "black gold"],
  "calm": ["serene", "tranquil", "peaceful", "quiet"],
  "clan": ["tribe", "family", "clique", "kin"],
  "nova": ["supernova", "stellar explosion", "celestial event", "starburst"],
  "lean": ["slender", "thin", "skinny", "trim"],
  "mole": ["blemish", "spot", "mark", "discoloration"],
  "mane": ["hair", "tresses", "lock", "mane of a lion"],
  "mace": ["club", "staff", "bludgeon", "baton"],
  "acne": ["pimples", "blemishes", "zits", "skin condition"],
  "acorn": ["nut", "seed", "oak nut", "seed of an oak tree"],
  "lemon": ["citrus fruit", "yellow fruit", "sour fruit", "lemonade"],
  "melon": ["fruit", "cantaloupe", "watermelon", "muskmelon"],
  "lame": ["disabled", "crippled", "impaired", "limping"],
  "lace": ["cord", "ribbon", "thread", "string"],
  "cane": ["walking stick", "staff", "rod", "pole"],
  "clove": ["spice", "seasoning", "herb", "aromatic"],
  "clam": ["mollusk", "shellfish", "bivalve", "seashell"],
  "enclave": ["enclosed area", "territory", "region", "district"],
  "venom": ["poison", "toxin", "venin", "noxious substance"]
};

const dictionary = {
  book: "A set of written or printed pages, usually bound with a protective cover.",
      chair: "A separate seat for one person, typically with a back and four legs.",
      table: "A piece of furniture with a flat top and one or more legs, providing a level surface for eating, writing, or working.",
      car: "A road vehicle, typically with four wheels, powered by an internal combustion engine and able to carry a small number of people.",
      pen: "An instrument for writing or drawing with ink, typically consisting of a metal nib or ball, or a nylon tip, fitted into a metal or plastic holder.",
      computer: "An electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program.",
      phone: "a device by which sound (such as speech) is converted into electrical impulses and transmitted (as by wire or radio waves) to one or more specific receivers.",
      house: "A building for human habitation, especially one that is lived in by a family or small group of people.",
      shoes: "A covering for the foot, typically made of leather, with a sturdy sole and not reaching above the ankle.",
      key: "A small piece of shaped metal with incisions cut to fit the wards of a particular lock, and that is inserted into a lock and turned to open or close it.",
      door: "A hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle, or in the framework of a cupboard.",
      cup: "A small bowl-shaped container for drinking from, typically having a handle.",
      clock: "A mechanical or electrical device for measuring time, indicating hours, minutes, and sometimes seconds by hands on a round dial or by displayed figures.",
      bag: "A flexible container with an opening at the top, used for carrying things.",
      paper: "Material manufactured in thin sheets from the pulp of wood or other fibrous substances, used for writing, drawing, or printing on.",
      bed: "A piece of furniture for sleep or rest, typically a framework with a mattress and coverings.",
      window:"An opening in the wall or roof of a building or vehicle, typically with glass in it, to admit light or air and allow people to see out.",
      tree: "A woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground.",
      watch: "A small timepiece worn typically on a strap on one's wrist.",
      hat: "A shaped covering for the head worn for warmth, as a fashion item, or as part of a uniform.",
      dog: "A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, and a barking, howling, or whining voice.",
      cat: "A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws.",
      bird: "A warm-blooded egg-laying vertebrate distinguished by the possession of feathers, wings, and a beak.",
      fish: "A limbless cold-blooded vertebrate animal with gills and fins living wholly in water.",
      elephant: "A heavy plant-eating mammal with a prehensile trunk, long curved ivory tusks, and large ears.",
      lion: "A large tawny-colored cat that lives in prides, found in Africa and Northwestern India.",
      tiger: "A large solitary cat with a yellow-brown coat striped with black, native to the forests of Asia.",
      bear: "A large, heavy mammal with thick fur and a short tail that is native to North America and Eurasia.",
      horse: "A large domesticated mammal with solid hooves, a flowing mane and tail, used for riding, racing, and as a beast of burden.",
      rabbit: "A burrowing, gregarious, plant-eating mammal with long ears, long hind legs, and a short tail.",
      monkey: "A small to medium-sized primate that typically has a long tail, most kinds of which live in trees in tropical countries.",
      snake: "A long legless reptile that has no eyelids and a short tail.",
      turtle: "A slow-moving reptile with a shell into which it can retract its head and thick skin.",
      dolphin: "A small gregarious toothed whale that typically has a beaklike snout and a curved fin on the back.",
      penguin: "A flightless bird that lives in the Southern Hemisphere, especially in Antarctica.",
      giraffe: "A large African mammal with a very long neck and forelegs, having a coat patterned with brown patches separated by lighter lines.",
      kangaroo: "A large herbivorous marsupial with a long powerful tail and strongly developed hind limbs that enable it to travel by leaping.",
      zebra: "A wild animal native to Africa, closely related to the horse, with black and white stripes on its body.",
      wolf: "A wild carnivorous mammal of the dog family.",
      cheetah: "A large slender spotted cat found in Africa and parts of Asia.",
      cow: "A fully grown female animal of a domesticated breed of ox, kept to produce milk or beef.",
      sheep: "A domesticated ruminant mammal with a thick woolly coat and typically curly horns.",
      chicken: "A domestic fowl kept for its eggs or meat, especially a young one.",
      duck: "A waterbird with a broad flat bill, webbed feet, and a squat body.",
      frog: "A tailless amphibian with a short squat body, moist smooth skin, and very long hind legs for leaping.",
      butterfly: "A nectar-feeding insect with two pairs of large, typically brightly colored wings that are covered with microscopic scales.",
      bee: "A stinging winged insect that collects nectar and pollen, produces wax and honey, and lives in large communities.",
      spider: "An eight-legged predatory arachnid with an unsegmented body consisting of a fused head and thorax and a rounded abdomen.",
      snail: "A shelled gastropod mollusk, typically with a spiral shell.",
      octopus: "A sea creature with a soft, oval body and eight sucker-bearing.",
      person: ['A human being regarded as an individual.'],
      time: ['The measured or measurable period during which an action, process, or condition exists or continues.'],
      year: ['A unit of time that is equal to 12 months or 365 or sometimes 366 days.'],
      way: ['A method, style, or manner of doing something; an optional or alternative form of action'],
      day: ['A division of time equal to 24 hours and representing the average length of the period during which the earth makes one rotation on its axis'],
      thing: ['An inanimate material object as distinct from a living sentient being.'],
      man: ['An adult male human being.'],
      world: ['The earth, together with all of its countries and peoples'],
      life: ['The existence of an individual human being or animal.'],
      hand: ['The end part of a persons arm beyond the wrist, including the palm, fingers, and thumb.'],
      part: ['An amount or section which, when combined with others, makes up the whole of something.'],
      child: ['A young human being below the age of puberty or below the legal age of majority.'],
      eye: ['Each of a pair of globular organs of sight in the head of humans and vertebrate animals.'],
      woman: ['An adult female human being.'],
      place: ['A particular position, point, or area in space; a location.'],
      work: ['Activity involving mental or physical effort done in order to achieve a purpose or result.'],
      week: ['A period of seven days.'],
      case: ['An instance of a particular situation; an example of something occurring.'],
      point: ['Give force or emphasis to (words or actions).'],
      government: ['The group of people with the authority to govern a country or state; a particular ministry in office.'],
      childhood: ['The state or period of being a child.'],
      dream: ['A cherished aspiration, ambition, or ideal.'],
      goal: ['The object of a persons ambition or effort; an aim or desired result.'],
      power: ['The capacity or ability to direct or influence the behaviour of others or the course of events.'],
      money: ['Any object that is generally accepted as payment for goods and services and repayment of debts in a given country or socio-economic context'],
      success: ['The accomplishment of an aim or purpose.'],
      failure: ['A lack of success in doing or achieving something, especially in relation to a particular activity.'],
      happiness: ['The state of being happy.'],
      friendship: ['The emotions or conduct of friends; the state of being friends.'],
      education: ['The process of receiving or giving systematic instruction, especially at a school or university.'],
      health: ['The state of being free from illness or injury.'],
      home: ['The place where one lives permanently, especially as a member of a family or household.'],
      nature: ['The phenomena of the physical world collectively, including plants, animals, the landscape, and other features and products of the earth, as opposed to humans or human creations.'],
      business: ['A persons regular occupation, profession, or trade.'],
      weekend: ['Saturday and Sunday, especially regarded as a time for leisure.'],
      experience: ['Practical contact with and observation of facts or events.'],
      adventure: ['An unusual and exciting or daring experience.'],
      bubble: ['A thin sphere of liquid enclosing air or another gas.'],
      guitar: ['A stringed musical instrument, with a fretted fingerboard, typically incurved sides, and six or twelve strings, played by plucking or strumming with the fingers or a plectrum.'],
      window: ['An opening in the wall or roof of a building or vehicle, fitted with glass in a frame to admit light or air and allow people to see out.'],
      dragon: ['A mythical monster resembling a giant reptile, sometimes shown as having wings. In European tradition the dragon is typically fire-breathing and tends to symbolize chaos or evil, whereas in East Asia it is usually a beneficent symbol of fertility, associated with water and the heavens.'],
      rocket: ['A cylindrical projectile that can be propelled to a great height or distance by the combustion of its contents, used typically as a firework or signal.'],
      circle: ['A round plane figure whose boundary (the circumference) consists of points equidistant from a fixed point (the centre).'],
      basket: ['A container used to hold or carry things, typically made from interwoven strips of cane or wire.'],
      coffee: ['A hot drink made from the roasted and ground seeds (coffee beans) of a tropical shrub.'],
      flower: ['The seed-bearing part of a plant, consisting of reproductive organs (stamens and carpels) that are typically surrounded by a brightly coloured corolla (petals) and a green calyx (sepals).'],
      lemon: ['A pale yellow oval citrus fruit with thick skin and fragrant, acidic juice.'],
      radio: ['The transmission and reception of electromagnetic waves of radio frequency, especially those carrying sound messages.'],
      table: ['A piece of furniture with a flat top and one or more legs, providing a level surface for eating, writing, or working at.'],
      ocean: ['A very large expanse of sea, in particular each of the main areas into which the sea is divided geographically.'],
      rabbit: ['A gregarious burrowing plant-eating mammal, with long ears, long hind legs, and a short tail.'],
      wallet: ['A pocket-sized flat folding case for holding money and plastic cards.'],
      bridge: ['A structure carrying a road, path, railway, etc. across a river, road, or other obstacle'],
      love: ['An intense feeling of deep affection'],
      friend: ['A person with whom one has a bond of mutual affection, typically one exclusive of sexual or family relations'],
      family: ['A family is a group of two or more persons related by birth, marriage, or adoption who live together; all such related persons are considered as members of one family'],
      house: ['A building for human habitation, especially one that consists of a ground floor and one or more upper storeys'],
      car: ['A four-wheeled road vehicle that is powered by an engine and is able to carry a small number of people'],
      money: ['Current medium of exchange in the form of coins and banknotes; coins and banknotes collectively'],
      school: ['A place or institution for teaching and learning; establishment for education, an institution for teaching children'],
      book: ['A written or printed work consisting of pages glued or sewn together along one side and bound in covers.'],
      city: ['An inhabited place of greater size, population, or importance than a town or village'],
      food: ['Any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life and growth'],
      water: ['A colourless, transparent, odourless liquid that forms the seas, lakes, rivers, and rain and is the basis of the fluids of living organisms'],
      air: ['The invisible gaseous substance surrounding the earth, a mixture mainly of oxygen and nitrogen'],
      health: ['The state of being free from illness or injury'],
      mind: ['The element of a person that enables them to be aware of the world and their experiences, to think, and to feel; the faculty of consciousness and thought'],
      heart: [' Hollow muscular organ that pumps the blood through the circulatory system by rhythmic contraction and dilation'],
      music: ['Vocal or instrumental sounds (or both) combined in such a way as to produce beauty of form, harmony, and expression of emotion'],
      art: ['The various branches of creative activity, such as painting, music, literature, and dance'],
      computer: ['An electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program'],
      internet: ['A global computer network providing a variety of information and communication facilities, consisting of interconnected networks using standardized communication protocols'],
      friendship: ['The emotions or conduct of friends; the state of being friends'],
      environment: ['The surroundings or conditions in which a person, animal, or plant lives or operates'],
      technology: ['The application of scientific knowledge for practical purposes, especially in industry'],
      communication: ['The imparting or exchanging of information by speaking, writing, or using some other medium'],
      culture: ['The ideas, customs, and social behaviour of a particular people or society'],
      problem: ['A matter or situation regarded as unwelcome or harmful and needing to be dealt with and overcome'],
      solution: ['A means of solving a problem or dealing with a difficult situation'],
      development: ['An event constituting a new stage in a changing situation'],
      economy: ['The state of a country or region in terms of the production and consumption of goods and services and the supply of money'],
      industry: ['Economic activity concerned with the processing of raw materials and manufacture of goods in factories'],
      opportunity: ['A time or set of circumstances that makes it possible to do something'],
      knowledge: ['Facts, information, and skills acquired through experience or education; the theoretical or practical understanding of a subject'],
      relationship: ['The way in which two or more people or things are connected, or the state of being connected.'],
      difference: ['A point or way in which people or things are dissimilar.'],
      decision: ['A conclusion or resolution reached after consideration,.'],
      future: ['A period of time following the moment of speaking or writing.'],
      spider: ['An eight-legged predatory arachnid with an unsegmented body consisting of a fused head and thorax and a rounded abdomen.'],
      penguin: ['A large flightless seabird of the southern hemisphere, with black upper parts and white underparts and wings developed into flippers for swimming under water'],
      ant:['A small insect typically having a sting and living in a complex social colony with one or more breeding queens.'],
      mud:['A slimy sticky mixture of solid material with a liquid and especially water.'],
      earth:['The planet on which we live'],
      hair:['Any of the fine threadlike strands growing from the skin of humans, mammals, and some other animals.'],
      pet:['A domestic or tamed animal kept for companionship or pleasure.'],
      pig:['An omnivorous domesticated hoofed mammal with sparse bristly hair and a flat snout for rooting in the soil.'],
      bird:['A warm-blooded egg-laying vertebrate animal distinguished by the possession of feathers, wings, a beak, and typically by being able to fly.'],
      barn:['A large farm building used for storing grain, hay, or straw or for housing livestock.'],
      moon:['The natural satellite of the earth, visible (chiefly at night) by reflected light from the sun.'],
      snap:['Break suddenly and completely, typically with a sharp cracking sound.'],
      heat:['The quality of being hot, high temperature.'],
      hit:['To bring your hand, or an object you are holding, against somebody/something quickly and with force.'],
      ice:['Frozen water, a brittle transparent crystalline solid.'],
      pirate:['A person who attacks and robs ships at sea.'],
      cave:['A natural underground chamber in a hillside or cliff.'],
      pact:['A formal agreement between individuals or parties.'],
      rice:['A swamp grass which is widely cultivated as a source of food, especially in Asia.'],
      rate:['A fixed price paid or charged for something.'],
      vice:['Immoral or wicked behaviour.'],
      carpet:['A floor covering made from thick woven fabric.'],
      chart:['A sheet of information in the form of a table, graph, or diagram.'],
      peach:['A round stone fruit with juicy yellow flesh and downy pinkish-yellow skin.'],
      teach:['Impart knowledge to or instruct (someone) as to how to do something.'],
      braid:['A length of hair made up of three or more interlaced strands.'],
      brain:['An organ of soft nervous tissue contained in the skull of vertebrates, functioning as the coordinating centre of sensation and intellectual and nervous activity.'],
      bind:['Tie or fasten (something) tightly together.'],
      bride:['A woman on her wedding day or just before and after the event.'],
      drape:['Long curtains'],
      drain:['Cause the water or other liquid in (something) to run out, leaving it empty or dry.'],
      diner:['A person who is eating, typically a customer in a restaurant.'],
      dine:['Eat dinner.'],
      earn:['Obtain (money) in return for labour or services.'],
      end:['A final part of something, especially a period of time, an activity, or a story.'],
      pad:['A thick piece of soft material, typically used to protect or shape something, or to absorb liquid.'],
      pan:['A metal container used for cooking food in.'],
      pane:['A single sheet of glass in a window or door.'],
      pair:['A set of two things used together or regarded as a unit'],
      pain:[' Highly unpleasant physical sensation caused by illness or injury.'],
      pear:['A yellowish- or brownish-green edible fruit that is typically narrow at the stalk and wider towards the base, with sweet, slightly gritty flesh.'],
      pine:['An evergreen coniferous tree which has clusters of long needle-shaped leaves.'],
      pride:['A feeling of deep pleasure or satisfaction derived from ones own achievements, the achievements of those with whom one is closely associated, or from qualities or possessions that are widely admired.'],
      rain:['The condensed moisture of the atmosphere falling visibly in separate drops.'],
      raise:['Lift or move to a higher position or level.'],
      ride:['A journey made on a horse, bicycle, or motorcycle, or in a vehicle.'],
      rib:['Each of a series of slender curved bones articulated in pairs to the spine (twelve pairs in humans), protecting the thoracic cavity and its organs.'],
      rise:['Move from a lower position to a higher one; come or go up.'],
      side:['A position to the left or right of an object, place, or central point.'],
      snare:['A trap for catching birds or mammals, typically one having a noose of wire or cord.'],
      spread:['Open out (something) so as to extend its surface area, width, or length.'],
      saber:['A heavy cavalry sword with a curved blade and a single cutting edge.'],
      sane:['(Of a person) of sound mind, not mad or mentally ill.'],
      sand:['A loose granular substance, typically pale yellowish brown, resulting from the erosion of siliceous and other rocks and forming a major constituent of beaches, river beds, the seabed, and deserts.'],
      send:['Cause to go or be taken to a particular destination; arrange for the delivery of, especially by post.'],
      seer:['A person of supposed supernatural insight who sees visions of the future.'],
      sine:['The trigonometric function that is equal to the ratio of the side opposite a given angle (in a right-angled triangle) to the hypotenuse.'],
      span:['The full extent of something from end to end; the amount of space that something covers.'],
      spin:['Turn or cause to turn or whirl round quickly.'],
      spine:['A series of vertebrae extending from the skull to the small of the back, enclosing the spinal cord and providing support for the thorax and abdomen; the backbone.'],
      bane:['A cause of great distress or annoyance.'],
      bean:['An edible seed, typically kidney-shaped, growing in long pods on certain leguminous plants.'],
      bare:['(Of a person or part of the body) not clothed or covered.'],
      brand:['A type of product manufactured by a particular company under a particular name.'],
      scribe:['A person who copies out documents, especially one employed to do this before printing was invented.'],
      arise:['To get up or come into existence.'],
      bends:['Curves or turns in a different direction.'],
      band:['A group of people joined together for a common purpose.'],
      pander:['To gratify or indulge someones weaknesses or vices.'],
      pared:['Reduced or trimmed down.'],
      resin:['A sticky substance obtained from plants or trees.'],
      rides:['Moves or travels by sitting in or on a vehicle.'],
      nerd:['Informal term for intellectually inclined or socially awkward individual.'],
      snipe:['To make a sly or petty verbal attack.'],
      snider:['Comparative form of "snide," displaying a mocking or derogatory attitude.'],
      sabre:['An edged weapon with a curved blade.'],
      serin:['A small finch-like bird found in Europe and Asia.'],
      spared:['Saved from harm or damage.'],
      panier:['A basket or container, especially one carried on the back of an animal.'],
      nadir:['The lowest point or moment of something.'],
      braised:['Cooked slowly in a closed container with a small amount of liquid.'],
      snare:['A trap for catching animals or something that entangles or catches.'],
      debris:['Scattered pieces of waste or remains.'],
      braid:['To weave together strands of hair or other materials.'],
      napes:['The back of the neck or a similar area in animals.'],
      bedpan:['A shallow container used by bedridden patients for urination or defecation.'],
      rapine:['The violent seizure of someones property.'],
      insider:['Someone with privileged or confidential information about a situation or organization.'],
      bud:['A small swelling on a branch that grows into a leaf, flower, or shoot.'],
      bug:['An insect, often referring to small creatures with six legs.'],
      burp:['The release of gas from the stomach through the mouth, accompanied by a sound.'],
      burden:['A heavy load or something that is emotionally difficult to bear.'],
      budge:['To move slightly or change position after being stuck or immovable.'],
      brine:['Water saturated or strongly impregnated with salt.'],
      burn:['To undergo combustion or be consumed by fire.'],
      ding:['To dent or make a small indentation on a surface.'],
      dire:['Extremely serious or urgent.'],
      dune:['A hill or ridge of sand formed by the wind.'],
      drug:['A substance that affects the functioning of the body, often used as medicine.'],
      grin:['A wide smile expressing happiness or amusement.'],
      grind:['To crush or pulverize something into small particles.'],
      grid:['A framework of parallel or intersecting lines.'],
      grip:['To hold tightly or firmly.'],
      guide:['A person who leads or directs others on a journey.'],
      grub:['Larvae of certain insects, or slang for food.'],
      nudge:['To push gently or persistently.'],
      nude:['Not clothed or without clothing.'],
      rein:['A strap or rope attached to a horses bridle for control.'],
      rend:['To tear or rip something into pieces.'],
      rude:['Lacking manners or being impolite.'],
      ruin:['Destruction or downfall, often resulting in dilapidation.'],
      run:['To move swiftly on foot.'],
      unbind:['To release from bonds or constraints.'],
      under:['Beneath or below something else.'],
      bruin:['A bear, especially in literature or folklore.'],
      rebind:['To bind again or secure with a fastening.'],
      buried:['Covered or hidden beneath the surface.'],
      burin:['A steel tool with a sharp point, used for engraving.'],
      unbred:['Not bred or having no offspring.'],
      reding:['An obsolete term for counseling or advising.'],
      inured:['Accustomed or hardened to something difficult or painful.'],
      bruined:['Made brown or discolored, often by exposure to the sun.'],
      nudger:['Someone or something that nudges or prompts.'],
      bunged:['Blocked or closed with a stopper.'],
      dubbing:['The process of adding a soundtrack to a film or video.'],
      dinger:['A solid hit or strong impact, especially in baseball.'],
      ring:['A circular band often worn as jewelry or for various purposes.'],
      urn:['A decorative vase often used to hold ashes or as an ornament.'],
      draw: ['Produce (a picture or diagram) by making lines and marks on paper with a pencil, pen, etc.'],
      armed:['Equipped with or carrying weapons, typically guns or knives.'],
      meant:['Past tense and past participle of the verb "mean," which can mean to intend or to signify.'],
      trade:['The act or process of buying, selling, or exchanging goods or services.'],
      tread:['The pattern of raised horizontal ridges on the surface of a tire or shoe, providing traction.'],
      dewar:['A double-walled vessel used to store and transport liquefied gases, keeping them at a low temperature.'],
      under:['In or into a position below or beneath something.'],
      derma:['The skin, especially as a distinct layer.'],
      named:['Past tense and past participle of the verb "name," which means to give a name to someone or something.'],
      amend:['To make minor changes in order to improve or clarify something, especially a legal document.'],
      wane:['To decrease gradually in size, intensity, or degree.'],
      ante:['To place a bet before seeing ones own cards.'],
      taw:['To convert (skins) into leather by soaking in a liquid containing tannic acid.'],
      award:['A prize or other mark of recognition given in honor of an achievement.'],
      wader:['A waterproof boot extending from the foot to the chest, typically made of rubber or plastic, worn for walking in water.'],
      trawl:['To fish with a trawl net or seine.'],
      tan:['To convert (animal hide) into leather by soaking in a liquid containing tannic acid; also, the brown color acquired by the skin after exposure to the sun.'],
      mat:['A flat piece of material used as a surface to wipe the feet on, or a piece of coarse fabric for wiping ones shoes.'],
      dew:['Tiny drops of water that form on cool surfaces at night when atmospheric vapor condenses.'],
      date:['The day of the month or year as specified by a number.'],
      wand:['A thin, slender stick or rod, often magical in nature, used by wizards or magicians.'],
      dawn:['The first appearance of light in the sky before sunrise; the beginning or rise of something.'],
      rend:['To tear or split apart violently.'],
      dart:['A small, pointed missile that can be thrown or fired.'],
      ward:['A person, especially a child, who is under the protection or care of someone.'],
      tear:['To damage or rip apart by pulling forcefully.'],
      dear:['Loved or cherished; highly valued.'],
      want:['To have a desire for something; a lack or deficiency of something.'],
      read:['To look at and comprehend the meaning of written or printed matter by interpreting the characters or symbols.'],
      mate:['A partner or companion; to bring together for breeding.'],
      tame:['Domesticated or brought under human control; not wild.'],
      rate:['A measure, quantity, or frequency, usually in relation to another measure.'],
      near:['In close proximity; almost or nearly.'],
      eare:['Not occurring often; uncommon.'],
      dare:['To have the courage to do something; to challenge someone to do something difficult.'],
      darted:['Moved suddenly and quickly in a particular direction.'],
      wanted:['Desiring or wishing for something; desired by someone.'],
      warmed:['Made or become warm.'],
      disc:['A flat, thin, and typically round object with symmetrical sides, often used for playing games such as frisbee or as a storage medium for digital data.'],
      sun:['The star around which the Earth orbits, providing light and heat to the Earth; the source of daylight.'],
      scum:['A layer of impurities or undesirable material that forms on the surface of a liquid, often used colloquially to describe unpleasant or contemptible people.'],
      sin:['An immoral act considered to be a transgression against divine law; a wrongful or regrettable action.'],
      bat:['A mammal capable of sustained flight, typically with membranous wings. It can also refer to a piece of equipment used in sports such as baseball or cricket.'],
      rat:['A rodent known for its long tail and sharp teeth. It can also be used informally to describe a person who betrays or informs on others.'],
      tar:['A dark, thick, flammable liquid obtained from wood or coal, used as a road surfacing material or for waterproofing.'],
      bar:['A place where alcoholic beverages are served; a counter or area where drinks are prepared and served.'],
      sea: ['The expanse of saltwater covering the Earths surface, often divided into several recognized oceans.'],
      tea:['A hot or cold beverage made by infusing dried, crushed, or fermented leaves of the tea plant in hot water.'],
      eat:['To consume food by putting it in the mouth and swallowing.'],
      set:['To put something in a particular position or state; a collection of objects or scenery used for a particular scene in a play, movie, or television program.'],
      bet:['To risk money or valuables on the outcome of an event or a contest, typically with the expectation of winning additional money.'],
      hot:['Having a high temperature; spicy or pungent in flavor.'],
      hoe:['A gardening tool with a thin, flat blade used for loosening soil and removing weeds.'],
      toe:['One of the digits of the foot; the front part of the foot.'],
      sob:['To cry noisily while taking in short, sudden breaths.'],
      rob:['To take property unlawfully from a person or place.'],
      orb:['A spherical object; a celestial body such as the moon or a planet.'],
      era:['A period of time marked by distinctive events, developments, or figures.'],
      ear:['The organ of hearing; the external part of this organ.'],
      taro:['A tropical plant with a starchy root used as a vegetable.'],
      sort:['To arrange or classify in a particular way; a category or type.'],
      zest:['The outer colored peel of a citrus fruit used for flavoring; great enthusiasm or energy.'],
      zero:['The numerical value 0; nothing or no quantity.'],
      rote:['Mechanical or habitual repetition of something to be learned.'],
      roes:['The eggs of a female fish, especially when prepared as a delicacy.'],
      rose:['A type of flowering shrub or vine with thorns and fragrant flowers.'],
      hose:['A flexible tube conveying water or other fluid; a garment worn on the legs and feet.'],
      host:['A person who receives or entertains guests; a large number of people or things.'],
      shot:['The firing or discharge of a gun or other projectile; an attempt to score in a game.'],
      star:['A celestial body that emits light and heat due to nuclear reactions; a famous person.'],
      tsar:['An emperor or ruler in certain European countries.'],
      boat:['A small vessel for traveling on water.'],
      bota:['A leather wine bag typically used by Spanish shepherds.'],
      base:['The lowest part or foundation of something; morally low or without principles.'],
      bate:['To moderate or restrain; to reduce the force or intensity of something.'],
      beat:['To strike or hit repeatedly; a rhythmic unit in music.'],
      best:['Of the highest quality or excellence; surpassing all others.'],
      arts:['Creative endeavors such as painting, music, literature, or performing arts.'],
      hest:['An archaic or poetic term meaning a command or request.'],
      rest:['To cease work or movement in order to relax or recover strength; the state of being at peace or in tranquility.'],
      shoe:['A covering for the foot, typically made of leather, with a sturdy sole and not reaching above the ankle.'],
      hold:['To grasp or carry something with your hands, to keep something in place, or to possess or own something.'],
      echo:['A repetition or imitation of sound caused by the reflection of sound waves.'],
      field:['An area of land used for agricultural purposes or a specific area of study, expertise, or activity.'],
      "file": "A folder or collection of information stored together, or to arrange documents or data in a particular order.",
      "fold": "To bend or bring together parts, as in cloth or paper.",
      "lode": "A deposit of valuable ore within definite boundaries separating it from surrounding rocks.",
      "old": "Having lived for a long time; no longer young.",
      "doe": "A female deer.",
      "dice": "A small, cube-shaped object marked with one to six spots on each face, used in games of chance.",
      "die": "To cease living; undergo a sudden, violent death.",
      "fiddle": "To play the violin, especially in a nonclassical style.",
      "hole": "A hollow place in a solid body or surface.",
      "bore": "To drill a hole or tunnel into something; to make weary through dullness or repetition.",
      "road": "A wide path for vehicles or pedestrians; a route or way to get from one place to another.",
      "dome": "A rounded or hemispherical roof or ceiling; a building or structure with a dome.",
      "brag": "To boast or talk with excessive pride about one's achievements or possessions.",
      "mode": "A particular way or manner of doing something; a fashion or style.",
      "gear": "Equipment or machinery for a particular purpose; a mechanism that transmits motion in a machine.",
      "bead": "A small, usually round object with a hole for threading on a string; a droplet of liquid.",
      "made": "Past tense and past participle of the verb 'make,' meaning to create or construct.",
      "dear": "Regarded with deep affection; highly valued or precious.",
      "dare": "To have the courage to do something; to challenge someone to perform a task.",
      "drab": "Lacking brightness or interest; dull or monotonous in appearance.",
      "game": "An activity engaged in for entertainment or fun; a form of play with rules.",
      "demo": "A demonstration or public display of a product, process, or skill.",
      "bode": "To be an omen or indicator of a future event; to foreshadow.",
      "roam": "To move about or travel aimlessly; to wander or explore without a definite destination.",
      "ogre": "A cruel and terrifying giant or monster, typically depicted in folklore.",
      "grad": "Short for 'graduate,' a person who has successfully completed a course of study.",
      "mega": "Denoting a factor of one million; extremely large or powerful.",
      "gore": "Blood that has been shed, especially as a result of violence or injury.",
      "mare": "A female horse; a fully mature female of various other mammals, such as elephants or whales.",
      "goer": "A person who attends or regularly goes to a particular place or event.",
      "barm": "Yeast foam that forms on the top of fermenting beer; froth or foam.",
      "beam": "A long, sturdy piece of timber or metal used as a horizontal support in construction.",
      "bear": "A large, heavy mammal with shaggy fur and a robust build; to endure or carry a burden.",
      "brad": "A thin wire nail with a small, rounded head.",
      "doer": "A person who acts or performs a task; one who accomplishes something.",
      "dore": "A term used in metallurgy to describe a process of gilding or plating with gold.",
      "grade": "A level or stage in a process, a rank or class in a grading system.",
      "adobe": "A type of building material made from earth, typically used to make bricks.",
      "amber": "A hard, yellowish-brown substance often used in jewelry; a fossilized resin.",
      "bread": "A staple food made from flour, water, and yeast, typically baked or leavened.",
      "omega": "The last letter of the Greek alphabet; used to denote the last or final part of something.",
      "robe": "A long, loose outer garment, often worn as a symbol of office or authority.",
      "roam": "To move about or travel aimlessly; to wander or explore without a definite destination.",
      "alone": "Being by oneself; separate from others.",
      "move": "Changing position or place; to go from one place to another.",
      "love": "Deep affection, fondness, or an intense feeling of connection towards someone or something.",
      "came": "The past tense of the verb 'come,' indicating movement toward a particular location.",
      "oven": "A kitchen appliance or enclosed compartment used for cooking or baking food.",
      "name": "A word or term used for identification; also, to give a specific title or identity to someone or something.",
      "vale": "A valley, usually smaller and more enclosed than a valley.",
      "acme": "The point of highest achievement or excellence; the peak or highest point.",
      "loan": "An amount of money borrowed with an agreement to return it, usually with added interest.",
      "coal": "A black or dark brown combustible rock often used as fuel.",
      "calm": "A state of tranquility, absence of disturbance, or a peaceful condition.",
      "clan": "A group of people with a common ancestor or shared interests.",
      "nova": "A star that suddenly becomes much brighter and then gradually returns to its original brightness over a few months.",
      "lean": "To incline or bend in a particular direction; lacking excess or fat, thin.",
      "mole": "A small mammal with velvety fur and very small eyes; also, a small, often dark-colored spot on the skin.",
      "mane": "The long hair growing from the neck or upper part of the neck of certain animals, such as horses or lions.",
      "mace": "A spice made from the dried outer covering of the nutmeg seed; also, a ceremonial staff carried as a symbol of authority.",
      "acne": "A skin condition characterized by red pimples, especially on the face, due to inflamed or infected sebaceous glands.",
      "acorn": "The nut of an oak tree, typically oval and covered with a cupule.",
      "lemon": "A yellow, citrus fruit with sour taste; also, something that is disappointing or unsatisfactory.",
      "melon": "A juicy, typically round fruit with a smooth exterior, such as a watermelon or cantaloupe.",
      "lame": "Unable to walk properly due to injury or weakness; also used informally to describe something that is unconvincing or inadequate.",
      "lace": "A delicate fabric made of yarn or thread in an open web-like pattern; also, to fasten or tie with laces.",
      "cane": "A slender, flexible stem, often from bamboo, used as support or walking stick; also, the stems of certain plants.",
      "clove": "A dried flower bud from the clove tree, used as a spice; also, a segment or division of a bulb.",
      "clam": "A type of shellfish with two hinged shells; also, used informally to refer to being tight-lipped or silent.",
      "enclave": "A distinct territorial or cultural area enclosed within a larger territory.",
      "venom": "Poisonous secretion injected into prey by snakes, spiders, or certain other animals; also, used metaphorically to describe intense malice or spite."
};


const letterSets = [
  ["C", "V", "A", "I", "R", "H", "P", "E", "T"],
      ["S", "B", "I", "D", "I", "R", "N", "A", "E", "P"],
      ["P", "E", "B", "G", "R", "I", "N", "N", "U", "D"],
      ["W", "M", "A", "N", "T", "D", "T", "E", "R"],
      ["M", "U", "D", "C", "S", "N", "I"],
      ["E", "S", "R", "H", "Z", "A", "T", "B", "O"],
      ["F", "H", "C", "I", "D", "O", "E", "H", "L", "O"],
      ["M", "L", "V", "O", "N", "E", "O", "C", "A"],
      ["O", "B", "G", "D", "O", "R", "E", "A", "M"],
];

let currentSetIndex = 0;

function getRandomSet() {
return letterSets[currentSetIndex];
}

function addLetterButtons() {
const letterButtonsContainer = document.getElementById("letter-buttons-container");
letterButtonsContainer.innerHTML = "";

const randomLetters = getRandomSet();

randomLetters.forEach((letter) => {
  const button = document.createElement("button");
  button.textContent = letter;
  button.addEventListener("click", () => addToWord(letter));
  letterButtonsContainer.appendChild(button);
});
}

function addToWord(letter) {
const searchBox = document.getElementById("search-box");
searchBox.value += letter;
}

function clearSearchBox() {
const searchBox = document.getElementById("search-box");
searchBox.value = "";


const resultMessage = document.getElementById("result-message");
resultMessage.style.opacity = 0; 


setTimeout(function() {
  resultMessage.innerText = ""; 
  resultMessage.style.opacity = 1; 
}, 500); 

document.getElementById("definition").innerText = "";
document.getElementById("result-message").classList.remove("incorrect");
document.getElementById("synonyms").innerText = ""; 
}

function displayResultMessage(isCorrect) {
const resultMessage = document.getElementById("result-message");
resultMessage.textContent = isCorrect ? "Correct!" : "Incorrect!";
resultMessage.className = isCorrect ? "" : "incorrect";
}

function displayDefinition(word) {
const definitionDiv = document.getElementById("definition");
const synonymsDiv = document.getElementById("synonyms");

const definition = dictionary[word];
const synonyms = getSynonyms(word);

definitionDiv.textContent = `Definition: ${definition}`;

if (synonyms.length > 0) {
  synonymsDiv.textContent = `Synonyms: ${synonyms.join(", ")}`;
} else {
  synonymsDiv.textContent = "";
}
}

function getSynonyms(word) {
return Synonyms[word.toLowerCase()] || [];
}

function checkWord() {
const enteredWord = document.getElementById("search-box").value.toLowerCase();

if (enteredWord in dictionary) {
  displayResultMessage(true);
} else {
  displayResultMessage(false);
}

displayDefinition(enteredWord);
}

function nextSet() {
currentSetIndex = (currentSetIndex + 1) % letterSets.length;
clearSearchBox();
document.getElementById("result-message").textContent = "";
document.getElementById("result-message").className = "";
document.getElementById("definition").textContent = "";
addLetterButtons();
}


addLetterButtons();


function displayTranslation(translation) {
  const translationDiv = document.getElementById('translationResult');
  translationDiv.innerHTML = `<strong>Translation:</strong> ${translation}`;
}
const mascotButton = document.getElementById('mascotButton');
const toolsPopup = document.getElementById('toolsPopup');

mascotButton.addEventListener('click', () => {
toolsPopup.style.display = toolsPopup.style.display === 'block' ? 'none' : 'block';
});